package it.soft.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Utenti generated by hbm2java
 */
@Entity
@Table(name = "comuni", catalog = "db_condoni_guidonia")
public class Comune implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2067739759191453346L;
	/**
	 * 
	 */

	private Integer idcomuni;
	private String comune;
	private String provincia;
	private String regione;
//	private Set<Utenti> utenti;

	public Comune() {
	}

	public Comune(String comune, String provincia, String regione) {
		this.comune = comune;
		this.provincia = provincia;
		this.regione = regione;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idcomuni", unique = true, nullable = false)
	public Integer getIdcomuni() {
		return this.idcomuni;
	}

	public void setIdcomuni(Integer idcomuni) {
		this.idcomuni = idcomuni;
	}

	@Column(name = "comune", unique = true, length = 45)
	public String getComune() {
		return this.comune;
	}

	public void setComune(String comune) {
		this.comune = comune;
	}

	@Column(name = "provincia", unique = true, length = 45)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "regione", length = 45)
	public String getRegione() {
		return this.regione;
	}

	public void setRegione(String regione) {
		this.regione = regione;
	}

//	@OneToMany(cascade = CascadeType.ALL, mappedBy = "comune")
//	public Set<Utenti> getUtenti() {
//		return utenti;
//	}
//
//	public void setUtenti(Set<Utenti> utenti) {
//		this.utenti = utenti;
//	}

}
