package it.soft.domain;

// Generated 19-mar-2013 0.06.51 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Utenti generated by hbm2java
 */
@Entity
@Table(name = "utenti", catalog = "db_condoni_guidonia", uniqueConstraints = {
		@UniqueConstraint(columnNames = "password"),
		@UniqueConstraint(columnNames = "username") })
public class Utenti implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2067739759191453346L;
	/**
	 * 
	 */

	private BigDecimal idUtenti;
	private String username;
	private String password;
	private String nome;
	private String cognome;
	private String ruolo;
//	private Comune comune;

	public Utenti() {
	}

	public Utenti(String username, String password, String nome,
			String cognome, String ruolo) {
		this.username = username;
		this.password = password;
		this.nome = nome;
		this.cognome = cognome;
		this.ruolo = ruolo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idutenti", unique = true, nullable = false)
	public BigDecimal getIdUtenti() {
		return this.idUtenti;
	}

	public void setIdUtenti(BigDecimal idUtenti) {
		this.idUtenti = idUtenti;
	}

	@Column(name = "username", unique = true, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", unique = true, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cognome", length = 45)
	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	@Column(name = "ruolo", length = 45)
	public String getRuolo() {
		return this.ruolo;
	}

	public void setRuolo(String ruolo) {
		this.ruolo = ruolo;
	}

//	@ManyToOne(cascade = CascadeType.ALL)
//	@JoinColumn(name = "id_rel_comuni_utente")
//	public Comune getComune() {
//		return this.comune;
//	}
//
//	public void setComune(Comune comune) {
//		this.comune = comune;
//	}

	// @OneToMany(cascade = CascadeType.ALL, mappedBy = "utenti")
	// public Set<Turni> getTurnis() {
	// return this.turnis;
	// }
	//
	// public void setTurnis(Set<Turni> turnis) {
	// this.turnis = turnis;
	// }
	//
	// @OneToMany(cascade = CascadeType.ALL, mappedBy = "utenti")
	// public Set<Preferenze> getPreferenzes() {
	// return this.preferenzes;
	// }
	//
	// public void setPreferenzes(Set<Preferenze> preferenzes) {
	// this.preferenzes = preferenzes;
	// }

}
